app:
  title: Customer Manager

database:
  type: postgres

  "host": "ep-solitary-meadow-593229-pooler.ap-southeast-1.aws.neon.tech"
  "database": "meddb"
  "user": "sanjeev.dasgupta"
  "password": "npg_UbAvJimN3hE0"

entities:

  users:

    fields:

      - name: first_name
        label: First Name
        type: text
        required: true

      - name: last_name
        label: Last Name
        type: text
        required: true

      - name: age
        label: Age
        type: number
        validation:
          min: 18
          max: 120

      - name: email
        label: Email
        type: email
        required: true
        validation:
        email: true
        regex: "^[A-Z]{2}[0-9]{6}$"
        unique: true 

      - name: active
        label: Active
        type: checkbox

      - name: appointment_time
        label: Appointment
        type: date

      - name: gender
        label: Gender
        type: select
        options:
          - Male
          - Female

      - name: city
        label: City
        type: autocomplete
        options:
          - London
          - Paris
          - Delhi
          - Kolkata
          - Mumbai
          - Bangalore

      - name: document
        label: Resume
        type: file

        accept:
          - ".pdf"
          - ".docx"

        maxSizeMB: 20

        upload:
          endpoint: /api/upload

buttons:
  - save
  - cancel

table:

  columns:

    - first_name

    - last_name

    - age

    - email

    - active

actions:
    edit: true
    delete: true